import type { Question } from "./types";

export const corecsQuestions: Question[] = [
  // --- Operating systems ---------------------------------------------------
  {
    id: "os-1",
    moduleSlug: "corecs-os",
    prompt: "What is the actual difference between a process and a thread?",
    options: [
      "Threads are faster",
      "Threads of one process share an address space and open files; processes have their own, so the context switch costs more",
      "A process can have only one thread",
      "Threads cannot be scheduled independently",
    ],
    answer: 1,
    why: "Shared address space is why threads communicate cheaply and why one bad pointer takes down the whole process. It also explains why the switch is cheaper — no page-table swap.",
  },
  {
    id: "os-2",
    moduleSlug: "corecs-os",
    prompt: "Two threads run `counter++`. Why can the result be wrong even though it is one line of code?",
    options: [
      "The compiler reorders the line",
      "It is read, modify, write — three steps, and a switch between the read and the write loses an update",
      "Integers are not thread-safe types",
      "The cache is not flushed",
    ],
    answer: 1,
    why: "Non-atomicity of a compound operation is the definition of a race. Being able to name the three steps is what shows you understand rather than recite.",
  },
  {
    id: "os-3",
    moduleSlug: "corecs-os",
    prompt: "Deadlock requires four conditions to hold simultaneously. Breaking which one is the usual practical fix?",
    options: [
      "Mutual exclusion",
      "Circular wait — impose a global lock ordering so cycles cannot form",
      "Hold and wait",
      "No preemption",
    ],
    answer: 1,
    why: "Mutual exclusion is usually non-negotiable. A consistent lock acquisition order is the cheap, boring fix that works, which is why it is the standard answer.",
  },
  {
    id: "os-4",
    moduleSlug: "corecs-os",
    prompt: "A mutex and a binary semaphore look identical. What is the real difference?",
    options: [
      "None",
      "A mutex has ownership — only the locking thread may unlock it — while a semaphore may be signalled by any thread",
      "A semaphore cannot block",
      "A mutex cannot be used across processes",
    ],
    answer: 1,
    why: "Ownership is what enables priority inheritance and error checking on a mutex. It is also why a semaphore is the right primitive for signalling between threads, not for protecting a critical section.",
  },
  {
    id: "os-5",
    moduleSlug: "corecs-os",
    prompt: "What is thrashing?",
    options: [
      "Excessive context switching between threads",
      "The system spending more time servicing page faults than executing, because the working set does not fit in physical memory",
      "A disk failing under load",
      "A lock being contended by many threads",
    ],
    answer: 1,
    why: "It is a memory phenomenon: every access faults, and adding more processes makes it worse. The observable symptom is high disk I/O with near-zero useful CPU work.",
  },

  // --- DBMS ----------------------------------------------------------------
  {
    id: "db-1",
    moduleSlug: "corecs-dbms",
    prompt: "You add an index on a column and writes get slower. Why?",
    options: [
      "The index is corrupt",
      "Every insert, update and delete must also maintain the index structure",
      "Indexes lock the table",
      "The query planner stops using the primary key",
    ],
    answer: 1,
    why: "An index is a read optimisation paid for on write and in storage. 'Why not index every column' is the follow-up, and this is the answer.",
  },
  {
    id: "db-2",
    moduleSlug: "corecs-dbms",
    prompt: "A composite index on (a, b) — which query can use it efficiently?",
    options: [
      "WHERE b = 2",
      "WHERE a = 1 AND b = 2, and also WHERE a = 1 alone",
      "WHERE b = 2 AND a = 1 only if written in that order",
      "Any query touching either column",
    ],
    answer: 1,
    why: "Leftmost-prefix. The index is sorted by a then b, so b alone has no usable ordering — while the WHERE clause's written order does not matter at all.",
  },
  {
    id: "db-3",
    moduleSlug: "corecs-dbms",
    prompt: "What anomaly does READ COMMITTED still allow that REPEATABLE READ does not?",
    options: [
      "Dirty reads",
      "Non-repeatable reads — the same row read twice in one transaction can differ",
      "Lost updates",
      "Phantom reads only",
    ],
    answer: 1,
    why: "READ COMMITTED blocks dirty reads only. REPEATABLE READ additionally pins the rows you have read; phantoms — new rows matching your predicate — need SERIALIZABLE.",
  },
  {
    id: "db-4",
    moduleSlug: "corecs-dbms",
    prompt: "Third normal form, in one sentence?",
    options: [
      "Every table has a primary key",
      "Every non-key attribute depends on the key, the whole key, and nothing but the key",
      "No repeating groups in a column",
      "All foreign keys are indexed",
    ],
    answer: 1,
    why: "The three clauses map to 1NF, 2NF and 3NF in order. Being able to say it that compactly — and then say when you would denormalise anyway — is the complete answer.",
  },
  {
    id: "db-5",
    moduleSlug: "corecs-dbms",
    prompt: "A LEFT JOIN returns fewer rows than the left table has. What is the likely cause?",
    options: [
      "The join key has duplicates",
      "A WHERE clause filters on a right-table column, which discards the NULL-extended rows and turns it into an inner join",
      "The right table is empty",
      "LEFT JOIN never preserves all left rows",
    ],
    answer: 1,
    why: "The condition belongs in the ON clause, not WHERE. This is one of the most common real SQL bugs and it fails silently by returning plausible-looking data.",
  },

  // --- Computer networks ---------------------------------------------------
  {
    id: "cn-1",
    moduleSlug: "corecs-cn",
    prompt: "TCP versus UDP — what does TCP actually add?",
    options: [
      "Encryption",
      "Ordered, reliable delivery via sequence numbers, acknowledgements, retransmission and flow/congestion control",
      "Faster transmission",
      "Larger packet sizes",
    ],
    answer: 1,
    why: "None of it is encryption — that is TLS on top. Naming the mechanisms rather than saying 'TCP is reliable' is what separates an answer from a slogan.",
  },
  {
    id: "cn-2",
    moduleSlug: "corecs-cn",
    prompt: "A /26 subnet gives you how many usable host addresses?",
    options: ["64", "62", "30", "126"],
    answer: 1,
    why: "32 - 26 = 6 host bits, so 64 addresses, minus the network and broadcast addresses. The off-by-two is the entire question.",
  },
  {
    id: "cn-3",
    moduleSlug: "corecs-cn",
    prompt: "Why does the three-way handshake need three messages rather than two?",
    options: [
      "To exchange encryption keys",
      "Both directions must have their initial sequence number sent and acknowledged, and two messages can only do that for one direction",
      "To negotiate the packet size",
      "To check the firewall allows traffic",
    ],
    answer: 1,
    why: "It is a two-way synchronisation, and each direction costs a SYN plus an ACK — with the middle two combined into one packet.",
  },
  {
    id: "cn-4",
    moduleSlug: "corecs-cn",
    prompt: "Which layer does a router operate at, and what does it use to decide where to send a packet?",
    options: [
      "Layer 2, using MAC addresses",
      "Layer 3, using destination IP addresses against a routing table",
      "Layer 4, using port numbers",
      "Layer 7, using the Host header",
    ],
    answer: 1,
    why: "Switch is layer 2 with MACs, router is layer 3 with IPs, and a layer 7 load balancer reads the request itself. Placing a device on the right layer is half of most networking questions.",
  },
  {
    id: "cn-5",
    moduleSlug: "corecs-cn",
    prompt: "What does encapsulation mean as data moves down the stack?",
    options: [
      "The data is compressed at each layer",
      "Each layer prepends its own header to the payload it received from the layer above, and the receiver strips them in reverse",
      "Each layer encrypts the layer above",
      "The data is split into equal fragments per layer",
    ],
    answer: 1,
    why: "Headers nest like envelopes. It is why an Ethernet frame carries an IP packet carrying a TCP segment carrying your HTTP request, and why MTU limits cascade.",
  },
];
