import type { Question } from "./types";

export const devopsQuestions: Question[] = [
  // --- Linux ---------------------------------------------------------------
  {
    id: "lin-1",
    moduleSlug: "devops-linux-foundations",
    prompt: "You delete a 10 GB log file that nginx still has open. df shows no space freed. Why?",
    options: [
      "The filesystem needs a fsck",
      "The inode's link count dropped but an open file descriptor keeps it alive; space returns when nginx closes or restarts",
      "The file went to a trash directory",
      "df caches its output for 60 seconds",
    ],
    answer: 1,
    why: "unlink removes a directory entry, not the data. This is the classic 3 a.m. incident, and 'truncate it instead, or restart the holder' is the answer they want.",
  },
  {
    id: "lin-2",
    moduleSlug: "devops-linux-foundations",
    prompt: "A directory has permissions drwxr-x--- owned by root:deploy. You are in the deploy group. What can you do?",
    options: [
      "List and enter it, but not create files in it",
      "Nothing — you are not the owner",
      "Everything the owner can do",
      "Create files but not list them",
    ],
    answer: 0,
    why: "r lists names, x traverses, w creates or deletes entries. Group has r-x, so you can ls and cd but not write. Note that x without r lets you access a known filename without listing the directory.",
  },
  {
    id: "lin-3",
    moduleSlug: "devops-linux-foundations",
    prompt: "What does the setgid bit on a directory do?",
    options: [
      "Runs files in it as the group owner",
      "New files inside inherit the directory's group rather than the creator's primary group",
      "Prevents non-owners from deleting files",
      "Makes the directory read-only",
    ],
    answer: 1,
    why: "Group inheritance for shared directories. The 'cannot delete others' files' behaviour is the sticky bit, which is what /tmp uses — do not mix them up.",
  },
  {
    id: "lin-4",
    moduleSlug: "devops-linux-foundations",
    prompt: "Your systemd service dies on start and journalctl shows nothing useful. What is the most informative next step?",
    options: [
      "Add Restart=always",
      "systemctl status for the exit code, then run the exact ExecStart command by hand as the configured User",
      "Reboot",
      "Change Type=simple to Type=forking",
    ],
    answer: 1,
    why: "Most unit failures are a wrong path, a missing environment variable, or a permission the service user lacks. Running it as that user reproduces it immediately; Restart=always just hides the failure in a loop.",
  },
  {
    id: "lin-5",
    moduleSlug: "devops-linux-foundations",
    prompt: "A process ignores SIGTERM. What is the practical difference from SIGKILL?",
    options: [
      "SIGTERM is faster",
      "SIGTERM can be caught and handled, allowing a clean shutdown; SIGKILL cannot be caught and leaves no chance to flush state",
      "SIGKILL asks politely first",
      "There is none — both terminate immediately",
    ],
    answer: 1,
    why: "This is why systemd sends TERM, waits TimeoutStopSec, then KILL. A service that loses data on restart usually has no TERM handler.",
  },

  // --- Git -----------------------------------------------------------------
  {
    id: "git-1",
    moduleSlug: "devops-git",
    prompt: "What is the actual difference between merge and rebase?",
    options: [
      "Rebase is faster",
      "Merge creates a commit joining two histories; rebase replays your commits onto a new base, creating new commits with new hashes",
      "Rebase deletes the old branch",
      "Merge only works on tracked branches",
    ],
    answer: 1,
    why: "New hashes is the key fact — it is why rebasing shared branches forces everyone else to recover, and why the rule is 'rebase your local work, merge everything public'.",
  },
  {
    id: "git-2",
    moduleSlug: "devops-git",
    prompt: "You committed to main but meant to commit to a feature branch. Nothing is pushed. What is the clean fix?",
    options: [
      "git reset --hard, then redo the work",
      "git branch feature, then git reset --hard origin/main — the commit lives on the new branch",
      "git revert the commit",
      "git checkout -b feature — the commit moves with you",
    ],
    answer: 1,
    why: "Branch first (the label now points at your commit), then move main back. Note that checkout -b would carry the commit along on the new branch but leaves main still pointing at it.",
  },
  {
    id: "git-3",
    moduleSlug: "devops-git",
    prompt: "git reset --soft, --mixed and --hard differ how?",
    options: [
      "Only in speed",
      "soft moves HEAD only; mixed also resets the index; hard also overwrites the working tree, discarding changes",
      "soft keeps history, hard rewrites it",
      "hard is the only one that moves HEAD",
    ],
    answer: 1,
    why: "Three layers — HEAD, index, working tree — and each flag reaches one layer further. --hard is the only one that can lose uncommitted work.",
  },
  {
    id: "git-4",
    moduleSlug: "devops-git",
    prompt: "You force-pushed over a colleague's commits. Are they gone?",
    options: [
      "Yes, permanently",
      "No — if anyone still has them locally, git reflog finds the old tip and it can be restored",
      "Only if garbage collection has run on the server",
      "Yes, unless there was a tag",
    ],
    answer: 1,
    why: "Reflog is the undo history for branch tips and is the answer to almost every 'I destroyed something' question. Objects survive until gc prunes unreachable ones.",
  },
  {
    id: "git-5",
    moduleSlug: "devops-git",
    prompt: "What does git bisect actually do?",
    options: [
      "Splits a large commit into smaller ones",
      "Binary searches the commit range between a known-good and known-bad commit to find the one that introduced a bug",
      "Compares two branches",
      "Splits a repository in two",
    ],
    answer: 1,
    why: "Binary search over history — log2(n) checkouts instead of n. With `git bisect run <script>` it is fully automatic, which is the version worth mentioning in an interview.",
  },

  // --- Networking ----------------------------------------------------------
  {
    id: "net-1",
    moduleSlug: "devops-networking",
    prompt: "Your server has thousands of sockets in TIME_WAIT. What does that state mean?",
    options: [
      "The connection failed to establish",
      "The side that closed first waits ~2×MSL so late duplicate packets cannot corrupt a new connection reusing the same port pair",
      "The peer is not responding",
      "The socket is leaking",
    ],
    answer: 1,
    why: "TIME_WAIT is on the active closer and is correct behaviour, not a bug. Seeing thousands usually means your server closes connections rather than the client — often a missing keep-alive.",
  },
  {
    id: "net-2",
    moduleSlug: "devops-networking",
    prompt: "A DNS record change has not taken effect for some users. Why?",
    options: [
      "The record was typed wrong",
      "Resolvers cache the old answer until its TTL expires",
      "DNS uses TCP and the connection is stuck",
      "The domain needs re-registering",
    ],
    answer: 1,
    why: "TTL is the whole answer — and why you lower it before a planned migration and raise it afterwards.",
  },
  {
    id: "net-3",
    moduleSlug: "devops-networking",
    prompt: "In the TLS handshake, what is the certificate actually for?",
    options: [
      "Encrypting the traffic",
      "Binding a public key to a hostname, vouched for by a CA — it authenticates the server, while the session key does the encrypting",
      "Compressing the connection",
      "Storing the session key",
    ],
    answer: 1,
    why: "Authentication versus encryption. Without the certificate you would have an encrypted channel to someone — you just would not know who.",
  },
  {
    id: "net-4",
    moduleSlug: "devops-networking",
    prompt: "A request works with curl by IP but fails through the load balancer with a 502. Where do you look first?",
    options: [
      "DNS resolution",
      "The upstream health check and what the backend returned — 502 means the proxy reached upstream and got an invalid or no response",
      "The client's TLS version",
      "The firewall",
    ],
    answer: 1,
    why: "Reading status codes precisely narrows the search: 502 is upstream broken, 504 is upstream too slow, 503 is no healthy upstream at all. Each points at a different half of the system.",
  },
  {
    id: "net-5",
    moduleSlug: "devops-networking",
    prompt: "'Type a URL and press enter' — which ordering is right?",
    options: [
      "TCP handshake, DNS, TLS, HTTP request",
      "DNS resolution, TCP handshake, TLS handshake, HTTP request, response, render",
      "DNS, TLS, TCP, HTTP",
      "ARP, HTTP, DNS, TCP",
    ],
    answer: 1,
    why: "You need an address before you can connect, a connection before you can negotiate TLS, and TLS before you can send an encrypted request. Being able to walk this out loud is the drill.",
  },

  // --- Docker --------------------------------------------------------------
  {
    id: "dkr-1",
    moduleSlug: "devops-docker",
    prompt: "What is a container, mechanically?",
    options: [
      "A lightweight virtual machine with its own kernel",
      "A normal process, isolated by namespaces and limited by cgroups, sharing the host kernel",
      "A chroot with a network stack",
      "An image that has been extracted to disk",
    ],
    answer: 1,
    why: "Namespaces for what it can see, cgroups for what it can use, host kernel shared. That last part is why a Linux container cannot run on a Windows kernel and why kernel exploits cross the boundary.",
  },
  {
    id: "dkr-2",
    moduleSlug: "devops-docker",
    prompt: "Your image rebuilds from scratch every time you change one line of application code. What is wrong with the Dockerfile?",
    options: [
      "It is missing a .dockerignore",
      "COPY of the whole source happens before dependency installation, so the cached dependency layer is invalidated on every code change",
      "The base image is too large",
      "It needs --no-cache",
    ],
    answer: 1,
    why: "Copy the manifest, install dependencies, then copy the source. Layer caching is ordering, and this single reordering is usually the biggest build-time win available.",
  },
  {
    id: "dkr-3",
    moduleSlug: "devops-docker",
    prompt: "CMD versus ENTRYPOINT — what is the practical difference?",
    options: [
      "They are aliases",
      "ENTRYPOINT sets the executable and is not replaced by docker run arguments; CMD provides default arguments that run-time arguments override",
      "CMD runs at build time, ENTRYPOINT at run time",
      "Only one of them may appear in a Dockerfile",
    ],
    answer: 1,
    why: "ENTRYPOINT for 'this image is this program', CMD for its default arguments. Getting this wrong is why `docker run image bash` sometimes works and sometimes does not.",
  },
  {
    id: "dkr-4",
    moduleSlug: "devops-docker",
    prompt: "You baked a secret into a Dockerfile with ENV and then removed it in a later layer. Is it safe?",
    options: [
      "Yes, the final image no longer has it",
      "No — every layer is retained in the image history and the value is recoverable",
      "Yes, if you squash the image",
      "Only if the image is private",
    ],
    answer: 1,
    why: "Layers are additive and inspectable with docker history. Secrets belong in build secrets or runtime environment injection, never in a layer.",
  },
  {
    id: "dkr-5",
    moduleSlug: "devops-docker",
    prompt: "A container exits immediately with code 0 and no logs. Most likely cause?",
    options: [
      "It ran out of memory",
      "Its main process finished — a container lives exactly as long as PID 1, so a backgrounded or one-shot command ends it",
      "The image is corrupt",
      "The network is not attached",
    ],
    answer: 1,
    why: "Exit 0 means it succeeded and stopped. OOM would be 137. Reading the exit code first tells you which of these you are dealing with.",
  },
];
