import type { Question } from "./types";

/**
 * Phase 2 DevOps / SRE checkpoints. Each one is a situation, not a
 * definition: the wrong answers are what someone says after reading the docs
 * but before running the thing. Answer positions are balanced per module.
 */
export const devopsDepthQuestions: Question[] = [
  // --- AWS core ------------------------------------------------------------
  {
    id: "aws-1",
    moduleSlug: "devops-aws-core",
    prompt: "A role's identity policy allows s3:GetObject on a bucket, yet the call returns AccessDenied. Which is the most likely cause?",
    options: [
      "IAM changes take up to 24 hours to propagate",
      "An explicit Deny, an SCP or a permissions boundary that does not include the action",
      "The Allow must also be repeated in the bucket's ACL",
      "GetObject needs s3:* rather than a single action",
    ],
    answer: 1,
    why: "An explicit Deny anywhere wins, and SCPs and boundaries cap what an Allow can grant. Those — plus a Condition that did not match — are the places to look. IAM changes are eventually consistent within seconds, not hours.",
  },
  {
    id: "aws-2",
    moduleSlug: "devops-aws-core",
    prompt: "What makes a subnet in a VPC \"public\"?",
    options: [
      "It was created with the public-subnet checkbox",
      "Its security group allows 0.0.0.0/0 inbound",
      "It contains a NAT gateway",
      "Its route table sends 0.0.0.0/0 to an internet gateway",
    ],
    answer: 3,
    why: "Public is a routing property. Security groups are per interface, and a NAT gateway lives in a public subnet rather than making one.",
  },
  {
    id: "aws-3",
    moduleSlug: "devops-aws-core",
    prompt: "Responses from your web servers stop arriving after you add a network ACL that allows inbound 443. Why?",
    options: [
      "NACLs are stateless, so outbound traffic to the client's ephemeral ports needs its own allow rule",
      "NACLs apply only to UDP unless TCP is explicitly enabled on the subnet",
      "A NACL overrides the security group, so the SG's outbound rules are now ignored",
      "Port 443 must be allowed in both directions on the security group as well",
    ],
    answer: 0,
    why: "Security groups are stateful and allow return traffic automatically; NACLs are not. The response goes to the client's ephemeral port (1024–65535), which needs an outbound rule.",
  },
  {
    id: "aws-4",
    moduleSlug: "devops-aws-core",
    prompt: "Why require IMDSv2 on EC2 instances?",
    options: [
      "It serves metadata over HTTPS, so credentials cannot be sniffed on the host network",
      "IMDSv1 exposes the instance's SSH keys, which IMDSv2 stores in Secrets Manager instead",
      "It needs a session token from a PUT request, so a server-side request forgery bug cannot simply GET the role's credentials",
      "It rotates the instance role's credentials every minute instead of every hour",
    ],
    answer: 2,
    why: "IMDSv1 answers any GET to 169.254.169.254 — including one an attacker tricks your app into making. The PUT-then-token handshake of IMDSv2 defeats the typical SSRF.",
  },
  {
    id: "aws-5",
    moduleSlug: "devops-aws-core",
    prompt: "You work in ap-south-1 and want a CloudWatch alarm on estimated charges. Where is the metric?",
    options: [
      "In ap-south-1, under the Billing namespace",
      "In every region, as a per-region estimate",
      "Only in the AWS Budgets console, not in CloudWatch",
      "Only in us-east-1, whichever region your resources run in",
    ],
    answer: 3,
    why: "Billing metrics are global and published only in us-east-1. AWS Budgets is the other way to get the same alert, and works without the region quirk.",
  },

  // --- CI/CD ---------------------------------------------------------------
  {
    id: "ci-1",
    moduleSlug: "devops-cicd",
    prompt: "Job `build` writes dist/ and job `deploy` (with `needs: build`) cannot find it. Why?",
    options: [
      "`needs` only orders jobs on the same runner, and this workflow uses two runner labels",
      "dist/ is in .gitignore, so the runner deletes it at the end of the build job",
      "Each job runs on a fresh runner; files must be passed with upload-artifact and download-artifact",
      "The deploy job must check out the same commit with fetch-depth: 0 to see build outputs",
    ],
    answer: 2,
    why: "Steps in one job share a machine; separate jobs do not. `needs` orders them but moves no files. Artifacts are the handoff.",
  },
  {
    id: "ci-2",
    moduleSlug: "devops-cicd",
    prompt: "Which cache key gives the most useful dependency cache?",
    options: [
      "deps-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}",
      "deps-${{ runner.os }}-${{ github.sha }}",
      "deps-${{ runner.os }}",
      "deps-${{ github.run_id }}",
    ],
    answer: 0,
    why: "The lockfile hash changes exactly when dependencies change. A key with the commit SHA or run ID never hits a previous cache; a key with only the OS never refreshes.",
  },
  {
    id: "ci-3",
    moduleSlug: "devops-cicd",
    prompt: "Your workflow deploys to AWS using OIDC. Which part actually stops a workflow in someone else's repository from assuming your role?",
    options: [
      "Marking the role ARN as a repository secret",
      "Setting `permissions: id-token: write` in your workflow",
      "Using the official aws-actions/configure-aws-credentials action",
      "The condition on the token's `sub` claim in the role's trust policy",
    ],
    answer: 3,
    why: "Any repository can obtain a GitHub OIDC token; the trust policy decides which ones AWS accepts. Without a `sub` condition naming your repo, the role is open to all of GitHub.",
  },
  {
    id: "ci-4",
    moduleSlug: "devops-cicd",
    prompt: "Why tag the deployed image with the commit SHA instead of only `latest`?",
    options: [
      "Registries reject pushes that reuse the `latest` tag",
      "You can tell exactly which code is running, and roll back by redeploying a previous SHA",
      "The SHA tag makes the image smaller",
      "Docker pulls SHA-tagged images faster because they skip the cache",
    ],
    answer: 1,
    why: "`latest` moves with every build, so it records nothing. An immutable SHA tag makes \"what is running?\" and \"go back one version\" trivial.",
  },
  {
    id: "ci-5",
    moduleSlug: "devops-cicd",
    prompt: "Version 2 renames a database column, and you deploy it blue-green. What goes wrong when you switch back to blue?",
    options: [
      "Nothing — blue-green always allows an instant rollback",
      "The load balancer caches green's DNS for an hour",
      "Blue expects the old column name, so it fails against the migrated schema",
      "Blue's instances were terminated when green went live",
    ],
    answer: 2,
    why: "Blue-green rolls back code, not data. A breaking schema change must be done expand–contract so both versions can run against the schema at every step.",
  },
  {
    id: "ci-6",
    moduleSlug: "devops-cicd",
    prompt: "What does a canary release need that a plain rolling deployment does not?",
    options: [
      "Metrics comparing the canary with the baseline, and a rule that stops the rollout if the canary is worse",
      "Double the production capacity, so the old and new versions can each take full traffic",
      "A feature flag for every change, so the canary can switch features off individually",
      "A separate database for the canary, so bad writes cannot reach production data",
    ],
    answer: 0,
    why: "The point of a canary is an automatic comparison — error rate and latency against the baseline — that halts the rollout. Without it, a canary is just a slow rollout. Double capacity is blue-green's cost.",
  },

  // --- IaC -----------------------------------------------------------------
  {
    id: "iac-1",
    moduleSlug: "devops-iac",
    prompt: "A plan shows `-/+` next to your RDS instance. What does that mean?",
    options: [
      "The instance will be destroyed and recreated, because a changed argument cannot be updated in place",
      "The instance will be updated in place, with a brief reboot during the maintenance window",
      "Terraform will import the existing instance into state before modifying it",
      "The change touches only metadata such as tags, so nothing on the instance changes",
    ],
    answer: 0,
    why: "`~` is an in-place update; `-/+` is replacement. For a database that can mean data loss, which is why plans are read and stateful resources get prevent_destroy.",
  },
  {
    id: "iac-2",
    moduleSlug: "devops-iac",
    prompt: "Why must terraform.tfstate not be committed to the repository?",
    options: [
      "Git corrupts large JSON files on merge, and state files grow past that size quickly",
      "Terraform regenerates it from the code on every run, so a committed copy is always stale",
      "It embeds the absolute paths of the machine it was created on, so it breaks elsewhere",
      "It stores resource attributes, including secrets, in plain text — and git gives no locking",
    ],
    answer: 3,
    why: "State holds passwords and keys in clear text. It also needs locking so two applies cannot run at once — a remote backend such as S3 with locking provides both protection and sharing.",
  },
  {
    id: "iac-3",
    moduleSlug: "devops-iac",
    prompt: "A teammate changed a security group rule in the console. What happens on the next `terraform apply`?",
    options: [
      "Terraform adopts the console change into the code automatically",
      "Terraform reverts the rule to what the code says",
      "Terraform fails with a state-corruption error",
      "Nothing, because Terraform only tracks resources it created in this run",
    ],
    answer: 1,
    why: "That is drift. The plan shows it and apply restores the declared state. To keep the change, put it in the code (or accept it with -refresh-only and then update the code).",
  },
  {
    id: "iac-4",
    moduleSlug: "devops-iac",
    prompt: "How is state locking done on an S3 backend in current Terraform?",
    options: [
      "It is not possible — S3 has no locking primitive, so teams serialise applies through CI",
      "Only with a DynamoDB table, which remains the approach HashiCorp recommends",
      "`use_lockfile = true`, an S3-native lock; DynamoDB locking still works but is deprecated",
      "By enabling S3 object versioning, so a second writer's version is rejected",
    ],
    answer: 2,
    why: "Terraform 1.10 added S3-native locking. The DynamoDB table many tutorials and interviewers mention still works but is deprecated. Versioning protects against bad writes, not concurrent ones.",
  },
  {
    id: "iac-5",
    moduleSlug: "devops-iac",
    prompt: "What is the safest way to keep a dev apply from ever touching production?",
    options: [
      "Use one state file and add an `env` tag to every resource",
      "Separate state per environment, for example one directory and backend key per environment",
      "Ask everyone to check `terraform workspace show` before applying",
      "Put prod resources behind `count = var.is_prod ? 1 : 0`",
    ],
    answer: 1,
    why: "With separate state, a dev plan cannot even see prod resources. Workspaces share a backend and a configuration, so selecting the wrong one is an easy mistake.",
  },
  {
    id: "iac-6",
    moduleSlug: "devops-iac",
    prompt: "You run the same Ansible playbook twice on a server. What should the second run report?",
    options: [
      "The same number of changes as the first run",
      "An error, because the packages are already installed",
      "Changes only for the handlers",
      "changed=0 — the tasks describe a state that is already true",
    ],
    answer: 3,
    why: "That is idempotency: modules like apt with state: present check before acting. Handlers only run when a notifying task changed something, so they do not run either.",
  },

  // --- Observability -------------------------------------------------------
  {
    id: "obs-1",
    moduleSlug: "devops-observability",
    prompt: "Someone wants to add a `user_id` label to http_requests_total. What is the problem?",
    options: [
      "Label values must be strings, so numeric IDs are silently dropped at scrape time",
      "It is fine as long as the IDs are hashed first, so no personal data is stored",
      "Label values are limited to 32 characters, so long IDs are truncated and collide",
      "Every distinct label value creates a new time series, so cardinality grows with the number of users",
    ],
    answer: 3,
    why: "Each label combination is a series held in memory. Unbounded values — user IDs, emails, request IDs — belong in logs and traces. Hashing does not reduce the number of series.",
  },
  {
    id: "obs-2",
    moduleSlug: "devops-observability",
    prompt: "Why prefer a histogram to a summary for request latency across several instances?",
    options: [
      "Summaries round observations to whole seconds, so sub-second latency is lost",
      "Histogram buckets add up across instances before the quantile is computed; summary quantiles cannot be combined",
      "Histograms keep every raw observation, so any percentile can be computed exactly later",
      "Summaries are pushed rather than scraped, so they need a Pushgateway per instance",
    ],
    answer: 1,
    why: "Percentiles do not average: the mean of five instances' p95s is not the fleet p95. Buckets are counts, so they sum, and histogram_quantile runs on the total.",
  },
  {
    id: "obs-3",
    moduleSlug: "devops-observability",
    prompt: "Which PromQL gives requests per second per route from a counter?",
    options: [
      "sum by (route) (http_requests_total)",
      "rate(sum by (route) (http_requests_total)[5m])",
      "sum by (route) (rate(http_requests_total[5m]))",
      "avg by (route) (http_requests_total[5m])",
    ],
    answer: 2,
    why: "Take rate() of each raw series first — it corrects counter resets — then sum. The raw counter only ever rises, and summing before rate() hides resets.",
  },
  {
    id: "obs-4",
    moduleSlug: "devops-observability",
    prompt: "Which of these should page someone at night?",
    options: [
      "The share of 5xx responses has been above the SLO threshold for 10 minutes",
      "CPU on one instance has been above 80% for 10 minutes",
      "A single log line containing ERROR",
      "Disk usage crossed 60%",
    ],
    answer: 0,
    why: "Page on symptoms users feel. High CPU with healthy responses is not an emergency; one error line is noise; 60% disk is a ticket, or a predict_linear alert if it is filling fast.",
  },
  {
    id: "obs-5",
    moduleSlug: "devops-observability",
    prompt: "An alert rule has `for: 5m`. The expression becomes true for 2 minutes, then false. What happens?",
    options: [
      "The alert fires for 2 minutes and then resolves",
      "The alert fires once the 5 minutes have passed, since it was true at some point",
      "The alert goes pending, then returns to inactive without ever firing",
      "Alertmanager holds it for 5 minutes and then sends it",
    ],
    answer: 2,
    why: "The expression must stay true for the whole `for` duration. Until then the alert is pending, and a blip that clears never fires — which is the point of `for`.",
  },
  {
    id: "obs-6",
    moduleSlug: "devops-observability",
    prompt: "What lets you follow one failing request across three services' logs?",
    options: [
      "Keeping all three services' logs in the same file",
      "A request ID generated at the edge, passed along and logged by every service",
      "Timestamps accurate to the millisecond",
      "Setting the log level to debug in production",
    ],
    answer: 1,
    why: "Timestamps interleave thousands of requests. A propagated request ID ties one request's lines together, and links them to its trace.",
  },

  // --- SRE -----------------------------------------------------------------
  {
    id: "sre-1",
    moduleSlug: "devops-sre",
    prompt: "Which is the best latency SLI for atlas?",
    options: [
      "Average response time over the last 30 days",
      "The share of valid requests served in under 300 ms, measured at the load balancer",
      "The slowest request of each day",
      "CPU utilisation of the API servers",
    ],
    answer: 1,
    why: "An SLI is good events over valid events. A threshold counts every slow request an average would hide, and measuring at the load balancer includes requests the app never saw.",
  },
  {
    id: "sre-2",
    moduleSlug: "devops-sre",
    prompt: "With a 99.5% availability SLO over 30 days, roughly how much full downtime does the error budget allow?",
    options: [
      "About 22 minutes",
      "About 36 hours",
      "About 3.6 hours",
      "About 43 minutes",
    ],
    answer: 2,
    why: "0.5% of 720 hours is 3.6 hours. 43 minutes is the budget for 99.9%, and 22 minutes for 99.95%.",
  },
  {
    id: "sre-3",
    moduleSlug: "devops-sre",
    prompt: "The error budget for the month is spent in week two. What does a sensible error budget policy do?",
    options: [
      "Freeze risky releases and prioritise reliability work until the budget recovers",
      "Lower the SLO to 99% for the rest of the month so the team is not blocked",
      "Nothing until the month ends, since the budget resets with the window",
      "Page the on-call engineer on every new error until the budget is back in credit",
    ],
    answer: 0,
    why: "The budget is a shared agreement: when it is gone, the team spends effort on reliability instead of features. Moving the target after missing it makes the SLO meaningless.",
  },
  {
    id: "sre-4",
    moduleSlug: "devops-sre",
    prompt: "The site went down right after a deploy. You are the on-call engineer. What comes first?",
    options: [
      "Find the root cause in the new code before changing anything",
      "Write the postmortem while the details are fresh",
      "Scale up the instances to add headroom",
      "Roll back the deploy to restore service, then investigate",
    ],
    answer: 3,
    why: "Mitigate first: the last change is the prime suspect, and rolling back ends the outage in minutes. Diagnosis happens after users are served again.",
  },
  {
    id: "sre-5",
    moduleSlug: "devops-sre",
    prompt: "Which postmortem action item is well written?",
    options: [
      "\"Add a readiness check that fails when the DB pool is exhausted — owner: me, due 10 Oct\"",
      "\"Engineers should be more careful when deploying on Fridays, especially after 5 pm\"",
      "\"Investigate the root cause further and report back to the team when it is found\"",
      "\"Human error — the engineer ran the wrong command\"",
    ],
    answer: 0,
    why: "A specific change, an owner and a date. \"Be more careful\" and \"human error\" are where a blameless investigation starts, not where it ends.",
  },
  {
    id: "sre-6",
    moduleSlug: "devops-sre",
    prompt: "Clients retry failed calls to a struggling service with exponential backoff. What does adding jitter fix?",
    options: [
      "It makes non-idempotent requests safe to retry, since duplicates arrive at different times",
      "It shortens the total time spent retrying, so clients give up sooner on a dead service",
      "It spreads out retries so clients that failed together do not all retry at the same instants",
      "It lets the circuit breaker move to half-open sooner, testing recovery earlier",
    ],
    answer: 2,
    why: "Without jitter, every client computes the same backoff schedule and the retries arrive in synchronised waves. Idempotency is a separate problem — solved with idempotency keys.",
  },
];
