import type { Question } from "./types";

/**
 * Phase 2 DSA checkpoints. Same rule as Phase 1: every question has a wrong
 * answer that sounds right if you have read about the topic but not solved
 * the problems. Answer positions are balanced per module (validateContent).
 */
export const dsaDepthQuestions: Question[] = [
  // --- Stacks & queues -----------------------------------------------------
  {
    id: "sq-1",
    moduleSlug: "dsa-stacks-queues",
    prompt: "A queue built from two stacks pops from the output stack, refilling it from the input stack only when it is empty. What is the cost of pop?",
    options: [
      "O(n) every time, because the stacks are reversed on each pop",
      "O(log n), because the output stack halves the work each refill",
      "O(1) amortised — each element is moved from input to output at most once",
      "O(1) worst case — a refill never moves more than one element",
    ],
    answer: 2,
    why: "A single pop can move n elements, so the worst case is O(n). But every element crosses between the stacks once in its lifetime, so n operations cost O(n) in total — O(1) amortised.",
  },
  {
    id: "sq-2",
    moduleSlug: "dsa-stacks-queues",
    prompt: "For Next Greater Element with a monotonic stack, what does the stack hold while you scan left to right?",
    options: [
      "Indices still waiting for a greater element, with values decreasing from bottom to top",
      "Every index seen so far, kept in sorted order by value",
      "Indices whose next greater element has already been found",
      "Values increasing from bottom to top, so the top is the maximum",
    ],
    answer: 0,
    why: "An element waits on the stack until something greater arrives and pops it — that arrival is its answer. Whatever remains is decreasing, because a greater value would have popped the smaller ones below it.",
  },
  {
    id: "sq-3",
    moduleSlug: "dsa-stacks-queues",
    prompt: "Each iteration of a monotonic-stack loop may pop many elements. What is the total time over an array of n?",
    options: [
      "O(n²), since the inner while loop can run n times",
      "O(n log n), because each pop is a comparison against a sorted stack",
      "O(n·k), where k is the largest number of pops in one iteration",
      "O(n) — each index is pushed once and popped at most once",
    ],
    answer: 3,
    why: "Count pushes and pops, not loop nesting. There are n pushes and at most n pops across the whole scan, so the work is O(n) no matter how the pops are distributed.",
  },
  {
    id: "sq-4",
    moduleSlug: "dsa-stacks-queues",
    prompt: "How does Min Stack return the minimum in O(1) after a pop removes the current minimum?",
    options: [
      "It rescans the stack after every pop",
      "Each entry stores the minimum of the stack at the moment it was pushed",
      "It keeps a sorted copy of the elements",
      "It keeps a min-heap alongside the stack",
    ],
    answer: 1,
    why: "Storing (value, min-so-far) — or a second stack of minimums — means popping restores the previous minimum automatically. A heap gives O(log n) and cannot remove the popped element cheaply.",
  },
  {
    id: "sq-5",
    moduleSlug: "dsa-stacks-queues",
    prompt: "In Largest Rectangle in Histogram, when bar i is popped from the increasing stack, what is the width of the rectangle using bar i's height?",
    options: [
      "From the new stack top (the previous smaller bar) to the current index, exclusive on both sides",
      "From index 0 to the current index",
      "Just bar i's own width, 1",
      "From bar i to the end of the array",
    ],
    answer: 0,
    why: "The bar being pushed is the first smaller one to the right; the bar left on the stack is the first smaller one to the left. Bar i's height extends across everything between them: width = right − left − 1.",
  },
  {
    id: "sq-6",
    moduleSlug: "dsa-stacks-queues",
    prompt: "Sliding Window Maximum keeps a deque of indices. What makes it O(n)?",
    options: [
      "The deque is re-sorted each step, which is cheap because it is nearly sorted",
      "It keeps exactly the last k elements, so each step scans only k",
      "The deque stays sorted, so a binary search finds the maximum in O(log k)",
      "Smaller elements behind a new one are dropped from the back, and expired indices from the front; each index enters and leaves once",
    ],
    answer: 3,
    why: "An element smaller than a newer one can never be a window maximum again, so it is discarded. The front is always the current maximum, and each index is added and removed at most once.",
  },

  // --- Binary trees --------------------------------------------------------
  {
    id: "bt-1",
    moduleSlug: "dsa-binary-trees",
    prompt: "Which traversal visits a binary tree level by level, and what does it use?",
    options: [
      "Inorder, with a stack",
      "Level order (BFS), with a queue",
      "Preorder, with recursion",
      "Postorder, with two stacks",
    ],
    answer: 1,
    why: "Preorder, inorder and postorder are all depth-first. Level order is BFS: a queue, and processing `q.size()` nodes at a time separates the levels.",
  },
  {
    id: "bt-2",
    moduleSlug: "dsa-binary-trees",
    prompt: "Computing the diameter by calling height() on both children at every node is O(n²). What makes it O(n)?",
    options: [
      "Memoising each node's height in a hash map keyed by its value",
      "Running a BFS from the root and taking the widest level",
      "Switching to an iterative traversal so there is no call overhead",
      "Returning the height from one post-order recursion and updating the diameter as a side effect",
    ],
    answer: 3,
    why: "The height function already visits every node once. At each node, left height + right height is the longest path through it — record the best, return 1 + max. One pass.",
  },
  {
    id: "bt-3",
    moduleSlug: "dsa-binary-trees",
    prompt: "In Binary Tree Maximum Path Sum, why does the recursion return only one branch to its parent?",
    options: [
      "A path that continues to the parent cannot fork, so it can use at most one child's branch",
      "To keep the recursion depth at O(log n) instead of O(n)",
      "Because returning both would count the node's value twice in the global answer",
      "Because a negative branch must be dropped before it reaches the parent",
    ],
    answer: 0,
    why: "Through a node, the best path may use both children — that is recorded in the global answer. But what goes up to the parent must stay a single path, so it is node + max(left, right, 0).",
  },
  {
    id: "bt-4",
    moduleSlug: "dsa-binary-trees",
    prompt: "What does the recursive LCA of p and q return at a node where p is found in the left subtree and q in the right?",
    options: [
      "p, because it was found first",
      "null",
      "The node itself — the two searches split here",
      "The left child",
    ],
    answer: 2,
    why: "Each call returns the node if it is p or q, otherwise whatever non-null result comes up from its children. When both sides return non-null, this node is where the paths diverge.",
  },
  {
    id: "bt-5",
    moduleSlug: "dsa-binary-trees",
    prompt: "Which pair of traversals is enough to rebuild a binary tree with distinct values uniquely?",
    options: [
      "Preorder and postorder",
      "Preorder and inorder",
      "Level order alone",
      "Inorder alone",
    ],
    answer: 1,
    why: "Preorder names the root; inorder splits the rest into left and right subtrees. Preorder + postorder cannot tell a lone left child from a lone right child.",
  },
  {
    id: "bt-6",
    moduleSlug: "dsa-binary-trees",
    prompt: "What does the right side view of a binary tree contain?",
    options: [
      "Every node reached by following right pointers from the root",
      "All leaves, right to left",
      "The right child of every node",
      "The last node of each level in level order",
    ],
    answer: 3,
    why: "A left-subtree node is visible when the right side is shorter. Following right pointers misses it; taking the last node per level does not.",
  },

  // --- Binary search trees -------------------------------------------------
  {
    id: "bst-1",
    moduleSlug: "dsa-bst",
    prompt: "What is the time complexity of search in a plain (non-self-balancing) BST with n nodes?",
    options: [
      "O(h) — O(log n) if balanced, O(n) in the worst case",
      "O(log n) always, because each step halves the remaining keys",
      "O(1) on average, like hashing, with O(n) only on collisions",
      "O(n log n), because every level must be compared",
    ],
    answer: 0,
    why: "Search walks one root-to-leaf path. Inserting sorted keys builds a chain of height n, so the worst case is linear. std::set is self-balancing (a red-black tree in practice) precisely to keep h at O(log n).",
  },
  {
    id: "bst-2",
    moduleSlug: "dsa-bst",
    prompt: "A validator checks left->val < node->val < right->val at every node. Which tree does it wrongly accept?",
    options: [
      "A tree with a single node",
      "A complete tree built from a sorted array",
      "Root 5 with right child 6, whose left child is 3",
      "An empty tree",
    ],
    answer: 2,
    why: "3 < 6 passes the local check, but 3 sits in 5's right subtree and must be greater than 5. The fix is to pass (low, high) bounds down, or to check that inorder is strictly increasing.",
  },
  {
    id: "bst-3",
    moduleSlug: "dsa-bst",
    prompt: "When deleting a BST node with two children, what replaces it?",
    options: [
      "Its left child",
      "Its inorder successor — the smallest node in its right subtree",
      "The root",
      "Its parent",
    ],
    answer: 1,
    why: "The successor is larger than everything on the left and smaller than the rest of the right, so the invariant holds. It has no left child, so removing it is the easy case. The inorder predecessor works too.",
  },
  {
    id: "bst-4",
    moduleSlug: "dsa-bst",
    prompt: "A BST iterator must support next() in O(1) amortised time using O(h) memory. What does it store?",
    options: [
      "The full inorder sequence in a vector, with an index into it",
      "A pointer to the current node, following parent links to find the next",
      "A queue of the current level, as in a level-order traversal",
      "A stack holding the left spine of the unvisited part of the tree",
    ],
    answer: 3,
    why: "Flattening uses O(n) memory. The stack pauses an iterative inorder: pop a node, push the left spine of its right child. Each node is pushed and popped once, so next() is O(1) amortised.",
  },
  {
    id: "bst-5",
    moduleSlug: "dsa-bst",
    prompt: "Two nodes of a BST were swapped by mistake. How many inversions can the inorder sequence have, and why does it matter?",
    options: [
      "Always exactly two, one at each swapped node's position",
      "Any number, since each swap disturbs a whole subtree",
      "One or two — one when the swapped nodes are adjacent in inorder, and the code must handle both",
      "None — the swap only changes the shape, and inorder is still sorted",
    ],
    answer: 2,
    why: "A non-adjacent swap creates two descents; an adjacent swap creates only one. Code that looks for exactly two misses the adjacent case.",
  },

  // --- Heaps & tries -------------------------------------------------------
  {
    id: "hp-1",
    moduleSlug: "dsa-heaps-tries",
    prompt: "To find the kth largest element of a large array, what is the standard heap solution?",
    options: [
      "A max-heap of all n elements, popped k times",
      "Sort descending and index k−1",
      "A min-heap of size k, popping whenever it exceeds k",
      "A max-heap of size k",
    ],
    answer: 2,
    why: "The min-heap holds the k largest so far with the smallest of them on top — exactly the one to evict. O(n log k) time and O(k) space, and it also works on a stream.",
  },
  {
    id: "hp-2",
    moduleSlug: "dsa-heaps-tries",
    prompt: "In C++, what does `priority_queue<int> pq;` give you?",
    options: [
      "A min-heap",
      "A max-heap — the largest element is on top",
      "A sorted vector",
      "A heap with decrease-key",
    ],
    answer: 1,
    why: "The default comparator is less<int>, which yields a max-heap. A min-heap needs priority_queue<int, vector<int>, greater<int>>. There is no decrease-key.",
  },
  {
    id: "hp-3",
    moduleSlug: "dsa-heaps-tries",
    prompt: "Merging k sorted lists with N elements in total using a min-heap of list heads costs:",
    options: [
      "O(N log k)",
      "O(N log N)",
      "O(N·k)",
      "O(k log N)",
    ],
    answer: 0,
    why: "The heap never holds more than k items, and each of the N elements is pushed and popped once. Merging the lists one after another is O(N·k).",
  },
  {
    id: "hp-4",
    moduleSlug: "dsa-heaps-tries",
    prompt: "In the two-heap running median, how are the halves stored?",
    options: [
      "Both halves in min-heaps",
      "The smaller half in a min-heap, the larger in a max-heap",
      "One heap of all elements, popped to the middle",
      "The smaller half in a max-heap, the larger in a min-heap",
    ],
    answer: 3,
    why: "The median sits at the boundary, so each half must expose its element nearest the middle: the largest of the small half, the smallest of the large half.",
  },
  {
    id: "hp-5",
    moduleSlug: "dsa-heaps-tries",
    prompt: "What can a trie answer that a hash set of the same words cannot?",
    options: [
      "Whether a word is present",
      "Which stored words start with a given prefix",
      "How many words are stored",
      "Lookups in O(1) independent of word length",
    ],
    answer: 1,
    why: "Both check membership in O(L). Only the trie shares prefixes along a path, so reaching the prefix node answers \"what starts with this?\" directly.",
  },
  {
    id: "hp-6",
    moduleSlug: "dsa-heaps-tries",
    prompt: "In Word Search II, what makes the trie approach faster than searching the grid once per word?",
    options: [
      "One DFS per cell walks the trie alongside the grid and stops as soon as the path is not a prefix of any word",
      "The trie keeps the words sorted, so each grid path is binary searched against them",
      "The trie lets cells be reused, so no visited marking is needed during the DFS",
      "The trie gives each word's first letter, so the DFS starts only from matching cells",
    ],
    answer: 0,
    why: "All words are searched together: a missing trie child prunes the grid path for every word at once. Removing found words keeps the search from repeating work.",
  },

  // --- Greedy --------------------------------------------------------------
  {
    id: "gr-1",
    moduleSlug: "dsa-greedy",
    prompt: "To keep the maximum number of non-overlapping intervals, you sort by:",
    options: [
      "Start time",
      "Length, shortest first",
      "End time",
      "The number of intervals each one overlaps",
    ],
    answer: 2,
    why: "The earliest-ending interval leaves the most room for the rest — that is the exchange argument. Sorting by start lets one long early interval block many; sorting by length fails when a short interval straddles two.",
  },
  {
    id: "gr-2",
    moduleSlug: "dsa-greedy",
    prompt: "Coins are {1, 3, 4} and the amount is 6. What does \"take the largest coin that fits\" produce?",
    options: [
      "4 + 1 + 1 — three coins, when 3 + 3 needs only two",
      "3 + 3 — two coins, which is optimal, since greedy is safe for any coin set with 1",
      "No answer — greedy takes 4, then gets stuck with 2 left and no coin of 2",
      "Six coins of 1, since greedy falls back to the smallest coin when stuck",
    ],
    answer: 0,
    why: "Greedy coin change is only safe for canonical systems like {1, 5, 10, 25}. Interview inputs promise no such thing, so Coin Change is DP.",
  },
  {
    id: "gr-3",
    moduleSlug: "dsa-greedy",
    prompt: "In Gas Station, the tank goes negative at index i while starting from s. What can you conclude?",
    options: [
      "Only s fails; try s + 1 next, since each start must be checked on its own",
      "No start works at all, because the tour already has a deficit",
      "The answer is i, since that is where the fuel ran out",
      "Every start from s through i fails, so the next candidate is i + 1",
    ],
    answer: 3,
    why: "Any start between s and i arrives at i with no more fuel than starting from s did, so it fails there too. That skip is what makes the solution one pass instead of O(n²).",
  },
  {
    id: "gr-4",
    moduleSlug: "dsa-greedy",
    prompt: "Why does Candy need two passes?",
    options: [
      "The first pass sorts the ratings so the second can hand out candy in order",
      "Each child's constraint involves both neighbours; one pass satisfies the left, the other the right",
      "One pass assigns candies and the other sums them, since both cannot be done together",
      "The children sit in a circle, so the second pass fixes the wrap-around",
    ],
    answer: 1,
    why: "A left-to-right pass handles \"more than my left neighbour\", a right-to-left pass handles the right; the max at each index satisfies both with the fewest candies.",
  },
  {
    id: "gr-5",
    moduleSlug: "dsa-greedy",
    prompt: "Which of these problems is correctly solved by a greedy choice?",
    options: [
      "0/1 knapsack",
      "Coin change with arbitrary denominations",
      "Longest increasing subsequence",
      "Fractional knapsack",
    ],
    answer: 3,
    why: "When items can be split, taking the best value-per-weight first never wastes capacity. In 0/1 knapsack the best-ratio item can leave space nothing else fills, so it needs DP.",
  },
];
