import type { Question } from "./types";

/**
 * Checkpoint questions are written to catch bluffing, not to test recall.
 * Every one of these has a wrong answer that sounds right if you have read
 * about the topic but never used it.
 */
export const dsaQuestions: Question[] = [
  // --- C++ & STL -----------------------------------------------------------
  {
    id: "stl-1",
    moduleSlug: "dsa-cpp-stl",
    prompt: "You push_back into a vector inside a loop and hold a reference to element 0 across iterations. What goes wrong?",
    options: [
      "Nothing — vector guarantees stable references",
      "The reference dangles once a reallocation moves the buffer",
      "The reference silently points at element 1 after each push",
      "push_back throws once capacity is exceeded",
    ],
    answer: 1,
    why: "Growing a vector reallocates and copies. Every iterator, pointer and reference into it is invalidated. This is the single most common C++ bug in interview code.",
  },
  {
    id: "stl-2",
    moduleSlug: "dsa-cpp-stl",
    prompt: "Why is unordered_map's O(1) lookup a worst-case O(n) in an interview answer?",
    options: [
      "Because hashing integers is slow",
      "Because rehashing happens on every insert",
      "Because adversarial or degenerate keys can collide into one bucket",
      "Because it stores keys in sorted order internally",
    ],
    answer: 2,
    why: "O(1) is average-case. All keys hashing to one bucket degrades to a linked-list scan — which is why some judges have anti-hash tests and why map (a balanced tree, guaranteed O(log n)) is sometimes the safer answer.",
  },
  {
    id: "stl-3",
    moduleSlug: "dsa-cpp-stl",
    prompt: "lower_bound(v.begin(), v.end(), x) returns what, exactly?",
    options: [
      "The first element strictly greater than x",
      "The first element not less than x",
      "The last element less than or equal to x",
      "end() if x is not present",
    ],
    answer: 1,
    why: "First element >= x. upper_bound gives the first > x, and their difference is the count of x. Getting this pair right is most of what binary-search-by-library looks like.",
  },
  {
    id: "stl-4",
    moduleSlug: "dsa-cpp-stl",
    prompt: "Your comparator for sort returns true when a <= b. What happens?",
    options: [
      "The sort is stable instead of unstable",
      "Nothing — it is equivalent to <",
      "Undefined behaviour: the comparator must be a strict weak ordering",
      "Elements compare equal and are left in place",
    ],
    answer: 2,
    why: "std::sort requires strict weak ordering — comp(a, a) must be false. A <= comparator can walk off the end of the range and crash. It is a real, silent, hard-to-reproduce bug.",
  },
  {
    id: "stl-5",
    moduleSlug: "dsa-cpp-stl",
    prompt: "Reading 10^6 integers with cin is slow. What is the actual fix, and why does it work?",
    options: [
      "Use scanf — it is a faster function",
      "sync_with_stdio(false) and untie cin from cout, removing per-operation flushing and C-stream syncing",
      "Read into a string first, then convert",
      "Increase the buffer with setvbuf",
    ],
    answer: 1,
    why: "By default the C++ streams stay synchronised with C stdio and cin is tied to cout, forcing a flush before every read. Turning both off is the whole trick — and you must then not mix cin with scanf.",
  },

  // --- arrays & sorting ----------------------------------------------------
  {
    id: "arr-1",
    moduleSlug: "dsa-arrays-sorting",
    prompt: "Kadane's algorithm keeps one running value. What is the invariant that makes it correct?",
    options: [
      "The running value is the maximum subarray sum seen so far",
      "The running value is the best subarray sum *ending at the current index*",
      "The running value is the sum of all positive elements so far",
      "The running value is the prefix sum minus the minimum prefix",
    ],
    answer: 1,
    why: "The state is 'best sum ending here', which is why the transition is max(x, best + x). Confusing it with the global answer is why people cannot reconstruct Kadane's under pressure.",
  },
  {
    id: "arr-2",
    moduleSlug: "dsa-arrays-sorting",
    prompt: "Quicksort is O(n log n) average but O(n²) worst case. When does the worst case actually happen?",
    options: [
      "When the array contains duplicates",
      "When the pivot consistently splits the array very unevenly — e.g. already-sorted input with a first-element pivot",
      "When the array is larger than cache",
      "When recursion depth exceeds log n",
    ],
    answer: 1,
    why: "The cost is about partition balance. Sorted input plus a naive pivot gives n levels of size-1 splits. Randomised or median-of-three pivots exist precisely to make this improbable.",
  },
  {
    id: "arr-3",
    moduleSlug: "dsa-arrays-sorting",
    prompt: "Why does the Dutch national flag partition use three pointers rather than two?",
    options: [
      "To make it stable",
      "To handle the equal-to-pivot region separately, so duplicates are not re-partitioned",
      "To allow parallel execution",
      "To avoid swapping",
    ],
    answer: 1,
    why: "Two-way partitioning on an array of mostly-equal elements degrades badly. The middle region collapses all equals in one pass — which is why it is the standard fix for quicksort on duplicate-heavy input.",
  },
  {
    id: "arr-4",
    moduleSlug: "dsa-arrays-sorting",
    prompt: "You need the count of subarrays summing to k. What makes the prefix-sum + hashmap approach work?",
    options: [
      "Sorting the prefix sums first",
      "That sum(i..j) = prefix[j] - prefix[i-1], so you look up how many earlier prefixes equal prefix[j] - k",
      "That all elements are positive",
      "Sliding a window while the sum exceeds k",
    ],
    answer: 1,
    why: "The hashmap counts earlier prefix values. Note the sliding-window alternative requires non-negative numbers — the prefix-sum version does not, which is the whole reason to reach for it.",
  },
  {
    id: "arr-5",
    moduleSlug: "dsa-arrays-sorting",
    prompt: "Two pointers moving toward each other requires what property of the input?",
    options: [
      "It must be sorted, or otherwise monotone in the quantity you are comparing",
      "It must contain no duplicates",
      "It must have even length",
      "It must fit in memory",
    ],
    answer: 0,
    why: "The technique works because moving a pointer provably changes the objective in one direction. Without that monotonicity you cannot discard a candidate, and the method is just a slow scan.",
  },

  // --- binary search -------------------------------------------------------
  {
    id: "bs-1",
    moduleSlug: "dsa-binary-search",
    prompt: "What in a problem statement should make you reach for binary search on the answer?",
    options: [
      "The array is sorted",
      "The answer is a number in a known range, and 'is X feasible?' is monotone — feasible for all values above (or below) some threshold",
      "The constraints are n <= 10^5",
      "The problem asks for a minimum",
    ],
    answer: 1,
    why: "Sortedness is a special case. The real trigger is a monotone predicate over the answer space — 'minimum capacity such that…', 'maximum size such that…'. Recognising that is the whole skill.",
  },
  {
    id: "bs-2",
    moduleSlug: "dsa-binary-search",
    prompt: "mid = (lo + hi) / 2 has a bug. Which one?",
    options: [
      "It rounds the wrong way for negative indices",
      "lo + hi can overflow for large values; lo + (hi - lo) / 2 does not",
      "It fails when lo == hi",
      "It requires the array length to be a power of two",
    ],
    answer: 1,
    why: "A famous bug that sat in the JDK for years. It rarely bites on array indices but does on binary search over a large value range — exactly the answer-space case.",
  },
  {
    id: "bs-3",
    moduleSlug: "dsa-binary-search",
    prompt: "In a rotated sorted array, how do you decide which half to search?",
    options: [
      "Compare mid to the target",
      "Determine which half is sorted by comparing arr[lo] to arr[mid], then check whether the target lies inside that sorted half",
      "Find the pivot first — there is no other way",
      "Search both halves and take whichever succeeds",
    ],
    answer: 1,
    why: "One half is always sorted. Identify it, test containment against its two ends, and recurse into the other half otherwise. Finding the pivot first also works but is a second pass you do not need.",
  },
  {
    id: "bs-4",
    moduleSlug: "dsa-binary-search",
    prompt: "Your binary search loops forever. What is the most likely cause?",
    options: [
      "The array is not sorted",
      "A boundary update that does not shrink the range — e.g. hi = mid when mid can equal hi",
      "The comparison uses <= instead of <",
      "Integer division rounds down",
    ],
    answer: 1,
    why: "Every iteration must strictly shrink [lo, hi]. Pick one invariant — half-open or closed — write it once, and reuse it forever rather than re-deriving the boundaries under pressure.",
  },
  {
    id: "bs-5",
    moduleSlug: "dsa-binary-search",
    prompt: "Binary search on a monotone real-valued function: what replaces the exact-match termination?",
    options: [
      "Loop until lo == hi",
      "A fixed number of iterations, or until hi - lo is below an epsilon",
      "Round to integers first",
      "It cannot be done on reals",
    ],
    answer: 1,
    why: "Reals never converge to equality. About 100 iterations, or a tolerance tied to the required precision, is the standard shape.",
  },

  // --- strings -------------------------------------------------------------
  {
    id: "str-1",
    moduleSlug: "dsa-strings",
    prompt: "Two strings are anagrams. What is the cheapest correct check for lowercase ASCII?",
    options: [
      "Sort both and compare — O(n log n)",
      "A 26-length frequency array, incremented for one and decremented for the other — O(n)",
      "Compare their hashes",
      "Compare the sum of character codes",
    ],
    answer: 1,
    why: "Counting is linear. The sum-of-codes trick is a classic wrong answer: 'ad' and 'bc' have the same sum. Anything that collapses a multiset to a single number will collide.",
  },
  {
    id: "str-2",
    moduleSlug: "dsa-strings",
    prompt: "Longest substring without repeating characters. Why is the sliding window O(n) and not O(n²)?",
    options: [
      "Because the inner loop runs at most a constant number of times",
      "Because each pointer only ever moves forward, so together they take at most 2n steps",
      "Because the character set is bounded",
      "Because the hashmap makes lookups O(1)",
    ],
    answer: 1,
    why: "Amortised analysis of the two pointers, not the lookup cost. The left pointer never goes back — this is the argument to say out loud when asked for the complexity.",
  },
  {
    id: "str-3",
    moduleSlug: "dsa-strings",
    prompt: "In C++, s.substr(i, j) inside a loop over a long string is a performance trap. Why?",
    options: [
      "substr is O(1) but returns a dangling reference",
      "substr allocates and copies, turning an O(n) scan into O(n²)",
      "substr invalidates iterators into s",
      "substr is undefined when j exceeds the length",
    ],
    answer: 1,
    why: "It builds a new string every call. Use indices, or string_view, when you only need to look. (substr does clamp j safely — that part is fine.)",
  },
  {
    id: "str-4",
    moduleSlug: "dsa-strings",
    prompt: "Grouping anagrams: what makes a good hashmap key?",
    options: [
      "The string itself",
      "A canonical form — the sorted string, or a 26-count signature",
      "The string length",
      "The sum of character codes",
    ],
    answer: 1,
    why: "You need a key that is identical for all members of a group and different across groups. Sorting is O(k log k) per word; the count signature is O(k) and is the better answer if asked to optimise.",
  },
  {
    id: "str-5",
    moduleSlug: "dsa-strings",
    prompt: "A palindrome check with two pointers must skip non-alphanumerics. What is the subtle bug people ship?",
    options: [
      "Forgetting to lowercase",
      "Advancing only one pointer past the skipped characters, or not re-checking the l < r bound after skipping",
      "Using <= instead of <",
      "Not handling the empty string",
    ],
    answer: 1,
    why: "Both pointers need their own skip loops, and each skip loop needs the bounds check — otherwise a string of all punctuation walks off the end.",
  },

  // --- recursion & backtracking -------------------------------------------
  {
    id: "rec-1",
    moduleSlug: "dsa-recursion-backtracking",
    prompt: "The pick / not-pick template generates subsets. What is its time complexity and why?",
    options: [
      "O(n²) — two choices per level",
      "O(2^n) nodes, and O(n · 2^n) if you copy the current subset at each leaf",
      "O(n log n) — the recursion tree has log n depth",
      "O(n!) — the same as permutations",
    ],
    answer: 1,
    why: "Two choices at each of n levels. The copy cost at the leaves is the part people forget, and it is what an interviewer is checking when they ask 'and the space?'",
  },
  {
    id: "rec-2",
    moduleSlug: "dsa-recursion-backtracking",
    prompt: "Generating subsets of an array with duplicates, how do you avoid duplicate subsets?",
    options: [
      "Deduplicate the result at the end with a set",
      "Sort first, then at each level skip a candidate equal to the previous one you already branched on",
      "Only recurse on distinct values",
      "Use a hashmap of seen subsets during recursion",
    ],
    answer: 1,
    why: "Sort-then-skip prunes the tree instead of cleaning up after it. The end-dedup answer works but is the brute-force one, and the interviewer will ask you to do better.",
  },
  {
    id: "rec-3",
    moduleSlug: "dsa-recursion-backtracking",
    prompt: "What actually makes backtracking different from brute-force enumeration?",
    options: [
      "It uses recursion",
      "It abandons a partial candidate as soon as it cannot be completed, pruning whole subtrees",
      "It memoises repeated states",
      "It explores breadth-first",
    ],
    answer: 1,
    why: "The pruning is the algorithm. N-Queens is only tractable because a conflicting placement kills an entire subtree immediately.",
  },
  {
    id: "rec-4",
    moduleSlug: "dsa-recursion-backtracking",
    prompt: "In N-Queens, what is the O(1) test for a diagonal conflict?",
    options: [
      "Scan the board each time",
      "Track occupied row + col and row - col values in two sets",
      "Compare against the previous queen only",
      "Use a 2D visited matrix",
    ],
    answer: 1,
    why: "Each diagonal has a constant row+col; each anti-diagonal a constant row-col. Two sets (plus one for columns) replace the board scan and are what makes the solution fast.",
  },
  {
    id: "rec-5",
    moduleSlug: "dsa-recursion-backtracking",
    prompt: "You mutate a shared vector during backtracking. What must happen on the way out of a branch?",
    options: [
      "Nothing — the recursion unwinds automatically",
      "Undo the mutation, restoring the state the caller handed you",
      "Copy the vector before recursing",
      "Clear the vector",
    ],
    answer: 1,
    why: "Push before, pop after — that symmetry is what 'backtracking' names. Copying instead works but multiplies the memory and is the slower answer.",
  },

  // --- bit manipulation ----------------------------------------------------
  {
    id: "bit-1",
    moduleSlug: "dsa-bit-manipulation",
    prompt: "Every element appears twice except one. XOR of everything gives the single element. Why?",
    options: [
      "XOR sorts the values",
      "XOR is associative and commutative, x ^ x = 0 and x ^ 0 = x, so the pairs cancel",
      "XOR counts set bits",
      "Because the array is sorted",
    ],
    answer: 1,
    why: "Self-inverse plus order-independence. Say those two properties out loud and the whole family of XOR problems opens up.",
  },
  {
    id: "bit-2",
    moduleSlug: "dsa-bit-manipulation",
    prompt: "What does n & (n - 1) do?",
    options: [
      "Sets the lowest zero bit",
      "Clears the lowest set bit",
      "Isolates the lowest set bit",
      "Negates n",
    ],
    answer: 1,
    why: "Clears the lowest set bit — so looping while n is non-zero counts set bits in O(popcount) rather than O(32). n & -n isolates that bit instead; keep the two straight.",
  },
  {
    id: "bit-3",
    moduleSlug: "dsa-bit-manipulation",
    prompt: "Iterating all subsets of an n-element set with a bitmask: what is the standard loop?",
    options: [
      "for mask in 0..2^n - 1, and test bit i with (mask >> i) & 1",
      "for i in 0..n, shift left by i",
      "Recursively, there is no iterative form",
      "for mask in 0..n², check mask % 2",
    ],
    answer: 0,
    why: "Each mask is one subset. The 2^n bound is why bitmask DP is only viable for n up to about 20.",
  },
  {
    id: "bit-4",
    moduleSlug: "dsa-bit-manipulation",
    prompt: "1 << 31 on a 32-bit signed int is a problem. Why?",
    options: [
      "It is always zero",
      "It overflows into the sign bit — undefined behaviour in C++; use 1u or 1LL",
      "The compiler rejects it",
      "It is fine, but slow",
    ],
    answer: 1,
    why: "Shifting into the sign bit of a signed type is UB. Every bitmask over 31 elements needs 1LL or an unsigned literal — a real bug that only appears on large inputs.",
  },
  {
    id: "bit-5",
    moduleSlug: "dsa-bit-manipulation",
    prompt: "Two elements appear once, all others twice. XOR everything gives a ^ b. What next?",
    options: [
      "Sort and scan",
      "Pick any set bit of a ^ b — the two differ there — and partition the array by that bit, XOR-ing each group",
      "Divide a ^ b by two",
      "Use a hashmap; XOR cannot do it",
    ],
    answer: 1,
    why: "A set bit in a ^ b is a bit where they differ, so it splits the array into two single-element problems. This is the standard follow-up and the reason the interviewer asked the easy version first.",
  },

  // --- linked lists --------------------------------------------------------
  {
    id: "ll-1",
    moduleSlug: "dsa-linked-lists",
    prompt: "What problem does a dummy head node actually solve?",
    options: [
      "It makes the list circular",
      "It removes the special case where the head itself is inserted or deleted",
      "It speeds up traversal",
      "It stores the length",
    ],
    answer: 1,
    why: "Every head-mutation branch disappears. If your list code has an `if (head == null)` at the top and another one for deleting the first node, a dummy head deletes both.",
  },
  {
    id: "ll-2",
    moduleSlug: "dsa-linked-lists",
    prompt: "Floyd's cycle detection: after the pointers meet, how do you find the cycle's start?",
    options: [
      "The meeting point is the start",
      "Reset one pointer to the head and advance both one step at a time; they meet at the start",
      "Walk backwards from the meeting point",
      "Count the cycle length, then advance that many nodes",
    ],
    answer: 1,
    why: "The distance from head to the cycle start equals the distance from the meeting point to it, going forward. Being able to state that is the difference between remembering the trick and understanding it.",
  },
  {
    id: "ll-3",
    moduleSlug: "dsa-linked-lists",
    prompt: "Reversing a singly linked list iteratively needs how many pointers, and why?",
    options: [
      "Two — current and previous",
      "Three — previous, current and next, because reassigning current->next destroys the only reference to the rest of the list",
      "One — the head",
      "Four, one per boundary",
    ],
    answer: 1,
    why: "Save next before you overwrite the link. Losing the tail is the classic bug and it is immediately visible if you draw three boxes before writing anything.",
  },
  {
    id: "ll-4",
    moduleSlug: "dsa-linked-lists",
    prompt: "Why is merge sort the right sort for a linked list, where quicksort is right for an array?",
    options: [
      "Merge sort is always faster",
      "Merge sort needs only sequential access and O(1) extra links, while quicksort's partitioning relies on random access",
      "Linked lists cannot be partitioned",
      "Merge sort is in-place on lists but not arrays",
    ],
    answer: 1,
    why: "Access pattern drives the choice. On a list, merging is pointer rewiring with no extra array — the O(n) space penalty that merge sort pays on arrays disappears.",
  },
  {
    id: "ll-5",
    moduleSlug: "dsa-linked-lists",
    prompt: "An LRU cache uses a hashmap plus a doubly linked list. What does each structure contribute?",
    options: [
      "The map stores values; the list stores keys",
      "The map gives O(1) lookup of a node; the list gives O(1) move-to-front and eviction from the tail",
      "The list gives O(1) lookup; the map keeps insertion order",
      "The map handles collisions; the list handles capacity",
    ],
    answer: 1,
    why: "Neither structure alone is O(1) for both operations. Being able to say which half does what — and why the list must be doubly linked, to unlink in O(1) — is the whole answer.",
  },
];
