import type { Question } from "./types";

export const sdeQuestions: Question[] = [
  // --- C++ internals -------------------------------------------------------
  {
    id: "cpp-1",
    moduleSlug: "sde-cpp-internals",
    prompt: "A function returns a pointer to a local variable. What happens?",
    options: [
      "The compiler copies it to the heap",
      "The pointer dangles — the stack frame is gone and dereferencing it is undefined behaviour",
      "It works but leaks memory",
      "It is fine for primitives",
    ],
    answer: 1,
    why: "Stack memory is reclaimed when the frame pops. It often 'works' in testing because nothing has reused the memory yet, which is what makes it dangerous.",
  },
  {
    id: "cpp-2",
    moduleSlug: "sde-cpp-internals",
    prompt: "What does RAII actually guarantee?",
    options: [
      "That memory is allocated lazily",
      "That a resource acquired in a constructor is released in the destructor, which runs on every exit path including exceptions",
      "That objects are reference-counted",
      "That allocation never fails",
    ],
    answer: 1,
    why: "'Every exit path, including exceptions' is the part that matters. It is why C++ has no finally block — the destructor is the finally block.",
  },
  {
    id: "cpp-3",
    moduleSlug: "sde-cpp-internals",
    prompt: "unique_ptr versus shared_ptr — when is shared_ptr the wrong choice?",
    options: [
      "Whenever performance matters at all",
      "When ownership is actually exclusive — shared_ptr adds atomic refcount overhead and can hide cycles that never free",
      "When the object is large",
      "When the object is on the stack",
    ],
    answer: 1,
    why: "Reach for unique_ptr by default. Cyclic shared_ptrs leaking is the standard follow-up question, and weak_ptr is the answer to it.",
  },
  {
    id: "cpp-4",
    moduleSlug: "sde-cpp-internals",
    prompt: "A base class with virtual methods is deleted through a base pointer and the derived destructor never runs. Why?",
    options: [
      "The derived class had no destructor",
      "The base destructor was not virtual, so the call was resolved statically",
      "delete does not call destructors on polymorphic types",
      "The object was allocated with new[]",
    ],
    answer: 1,
    why: "Non-virtual destructor plus deletion through a base pointer is undefined behaviour and a very common leak. If a class has any virtual function, its destructor should be virtual.",
  },
  {
    id: "cpp-5",
    moduleSlug: "sde-cpp-internals",
    prompt: "What does std::move actually do?",
    options: [
      "Moves the object's memory to a new address",
      "Nothing at runtime — it is a cast to an rvalue reference, which lets overload resolution pick a move constructor",
      "Frees the source object",
      "Copies and then deletes the original",
    ],
    answer: 1,
    why: "It is a cast, not an operation. The moving is done by whatever constructor gets selected, and a type with no move constructor silently copies instead.",
  },

  // --- OOP -----------------------------------------------------------------
  {
    id: "oop-1",
    moduleSlug: "sde-oop",
    prompt: "Encapsulation is often described as 'making fields private'. What is the better answer?",
    options: [
      "Hiding data from other developers",
      "Keeping the invariants of an object enforceable by controlling every path that can change its state",
      "Using getters and setters for every field",
      "Preventing inheritance",
    ],
    answer: 1,
    why: "A class with a getter and setter for every field is not encapsulated — it is a struct with extra typing. The point is that no caller can put the object in an invalid state.",
  },
  {
    id: "oop-2",
    moduleSlug: "sde-oop",
    prompt: "The Liskov Substitution Principle is violated when…",
    options: [
      "A subclass adds new methods",
      "A subclass strengthens a precondition or weakens a postcondition, so code written against the base breaks when handed the subclass",
      "A subclass overrides a method",
      "A class has more than one parent",
    ],
    answer: 1,
    why: "The Square-extends-Rectangle example is exactly this: setWidth's postcondition ('height unchanged') no longer holds. Substitutability is about behaviour, not the type checker.",
  },
  {
    id: "oop-3",
    moduleSlug: "sde-oop",
    prompt: "Dependency Inversion says high-level modules should not depend on low-level modules. Depend on what instead?",
    options: [
      "On the framework",
      "On abstractions — and the abstraction should be owned by the high-level module, not the low-level one",
      "On configuration files",
      "On interfaces defined by the database layer",
    ],
    answer: 1,
    why: "The second half is the part people miss. If your service defines the repository interface and the database implements it, the dependency arrow has genuinely been inverted.",
  },
  {
    id: "oop-4",
    moduleSlug: "sde-oop",
    prompt: "When is the Strategy pattern the right answer?",
    options: [
      "When you need one shared instance",
      "When a family of interchangeable algorithms should be selectable at runtime without the caller branching on type",
      "When you need to add behaviour to an existing class",
      "When object creation is expensive",
    ],
    answer: 1,
    why: "Strategy replaces a growing if/else over 'kind'. That refactor — conditional to polymorphism — is what an interviewer is usually probing for.",
  },
  {
    id: "oop-5",
    moduleSlug: "sde-oop",
    prompt: "Composition over inheritance — what is the concrete problem with deep inheritance?",
    options: [
      "It is slower at runtime",
      "Subclasses depend on the base's implementation details, so a base change breaks them — a tight coupling that composition avoids",
      "It uses more memory",
      "Most languages limit inheritance depth",
    ],
    answer: 1,
    why: "The fragile base class problem. Inheritance is the strongest coupling a language offers; composition lets you change one collaborator without breaking the rest.",
  },

  // --- REST & FastAPI ------------------------------------------------------
  {
    id: "api-1",
    moduleSlug: "sde-rest-fastapi",
    prompt: "PUT versus POST — what is the distinction that matters?",
    options: [
      "PUT is for updates, POST is for creates",
      "PUT is idempotent — the same request repeated leaves the same state; POST is not",
      "PUT requires an ID in the body",
      "POST is cacheable, PUT is not",
    ],
    answer: 1,
    why: "Idempotence, not create-versus-update. It is why a client can safely retry a PUT after a timeout and cannot safely retry a POST — which is where duplicate orders come from.",
  },
  {
    id: "api-2",
    moduleSlug: "sde-rest-fastapi",
    prompt: "A client sends a well-formed request that fails a business rule. Which status?",
    options: [
      "400 Bad Request",
      "422 Unprocessable Entity — the syntax is fine but the content is semantically invalid",
      "500 Internal Server Error",
      "200 with an error field",
    ],
    answer: 1,
    why: "400 is malformed, 422 is understood-but-unacceptable, 500 means you have a bug. Returning 200 with an error body is the anti-pattern that breaks every generic client and retry policy.",
  },
  {
    id: "api-3",
    moduleSlug: "sde-rest-fastapi",
    prompt: "Why store a password hash with bcrypt or argon2 rather than SHA-256?",
    options: [
      "SHA-256 is broken",
      "Fast hashes are the problem — bcrypt and argon2 are deliberately slow and salted, making large-scale brute force expensive",
      "SHA-256 output is too short",
      "They are encrypted rather than hashed",
    ],
    answer: 1,
    why: "SHA-256 is fast, which is exactly wrong here: a GPU tries billions per second. A tuneable work factor plus a per-password salt is the requirement.",
  },
  {
    id: "api-4",
    moduleSlug: "sde-rest-fastapi",
    prompt: "A JWT is stateless. What is the practical consequence?",
    options: [
      "It cannot carry user data",
      "You cannot revoke one before it expires without adding server-side state, such as a denylist",
      "It must be stored in a cookie",
      "It cannot be validated offline",
    ],
    answer: 1,
    why: "Statelessness is the feature and the cost. Short expiry plus refresh tokens, or a revocation list, are the two ways out — and 'we use JWT so logout is instant' is simply false.",
  },
  {
    id: "api-5",
    moduleSlug: "sde-rest-fastapi",
    prompt: "What makes an API 'production-shaped' beyond returning correct data?",
    options: [
      "Swagger documentation",
      "Validation, consistent error bodies, pagination, timeouts, request IDs in logs, and a health endpoint",
      "GraphQL support",
      "Being written in a fast language",
    ],
    answer: 1,
    why: "The operational surface is what separates a demo from a service. An endpoint that returns everything with no pagination and no timeout is one large customer away from an outage.",
  },
];
